### ISSUE TITLE
put this on bower?

### ISSUE THREAD

**Issue by bitinn** [Aaronius/injectorjs#1]
i recently looked through quite a few injector (browser-side) implementation, and personally think this one offers quite a good balance between lean api and flexibility, it would be a good idea to expose this repo through `bower`, no?

(though you need to come up with a different package name than `injector`)

**Comment by Aaronius** [comment]
Hey @bitinn,

Candidly, I don't see a future for bower. I'm going to close this as I don't have an intention to publish it to bower. Sorry if this is an inconvenience for you.
