### ISSUE TITLE
post inject handling

### ISSUE THREAD

**Issue by bitinn** [Aaronius/injectorjs#2]
One feature I do find quite helpful is a post inject callback, like this one:

https://github.com/biggerboat/injector.js#postconstructs

That way we can be flexible about when and where to inject.

**Comment by Aaronius** [comment]
Thanks @bitinn. I agree this would be nice. I'm curious to know why you didn't decide to use biggerboat's injector.js. Or maybe you did. It looks quite similar.

**Comment by bitinn** [comment]
yep i end up using that repo as their core functionality are largely the same, but I do find 2 things nice about your injector that isn't in alternatives:
- verbose naming: (`toConstructor` instead of `toValue` for class).
- able to overwrite `$inject` keyword.

**Comment by Aaronius** [comment]
Good to know. Thanks. I've added post-inject handling: f71d9ea087649e755800a77485799ed0d544b071.
